In [6]:
import numpy as np

In [87]:
X = [1, 2, 3, 4]
Y = np.array([1, 20, 30, 40])
a = 0.001

In [88]:
def scaling(x):
    def f(e):
        tmp0 = sum(x) / len(x)
        tmp1 = max(x) - min(x)
        return (e - tmp0) / tmp1
    return np.array(list(map(f, x)))
    
X_scaled = scaling(X)   
X_scaled

array([-0.5       , -0.16666667,  0.16666667,  0.5       ])

In [10]:
# Grad descent looking for h(x) to minimize cost func J (in notes)
def suma(x, y, f0, f1):
        n = len(x)
        cnt = 0
        s = 0
        while cnt < n:
            s = s + f0 + f1 * x[cnt] - y[cnt]
            cnt += 1
        return s
    
def suma1(x, y, f0, f1):
        n = len(x)
        cnt = 0
        s = 0
        while cnt < n:
            s = s + (f0 + f1 * x[cnt] - y[cnt]) * x[cnt]
            cnt += 1
        return s
def J(x, y, f0, f1):
    n = len(x)
    cnt = 0
    s = 0
    while cnt < n:
        s = s + (f0 + f1 * x[cnt] - y[cnt])**2
        cnt += 1
    return (1 / (2 * n)) * s
    

def g_d(x, y, alfa):
    af = np.array([0, 0])
    tmp = np.array([0,0])
    m = len(x)
    cnt = 0
    ma = alfa * (1 / m)
    delta = J(x, y, af[0], af[1])
    while delta > 0.00001:
        #print(af0, af1, ma, suma(X, Y, af0, af1), suma1(X, Y, af0, af1) )
        beg = J(x, y, af[0], af[1])
        tmp0 = af[0] - (ma *  suma(x, y, af[0], af[1]))
        tmp1 = af[1] - (ma * suma1(x, y, af[0], af[1]))
        af = np.array([tmp0, tmp1])
        cnt += 1
        end = J(x, y, af[0], af[1])
        delta = abs(end - beg)
        if cnt < 100000 and cnt > 99990:
            print(delta)
        #print(af, beg, end, cnt, af[0], af[1], tmp0, tmp1)
        #print(FI)
    return (af, cnt)

In [15]:
%time g_d(X, Y, a)


CPU times: user 492 ms, sys: 4 ms, total: 496 ms
Wall time: 496 ms


(array([ -8.36768686,  12.48493642]), 19626)

In [90]:
A = np.array([[1, 2, 3], [2, 4, 4], [3, 5, 5]])
A[0] # first index is upper index 
A[:,0] # 0 row
A0 = np.array([[1, 1, 1]])
np.concatenate((A0, A), axis=0)
A[1]

array([2, 4, 4])

In [72]:
A
B = np.c_[np.ones(3), A]

In [89]:
print(B)
X1 = np.array([5, 5, 5])
B[:, 1].dot(X1)
B

[[ 1.  1.  2.  3.]
 [ 1.  2.  4.  4.]
 [ 1.  3.  5.  5.]]


array([[ 1.,  1.,  2.,  3.],
       [ 1.,  2.,  4.,  4.],
       [ 1.,  3.,  5.,  5.]])

In [102]:
i = 0
while i < 4:
    print(B[:, i])
    i += 1

[ 1.  1.  1.]
[ 1.  2.  3.]
[ 2.  4.  5.]
[ 3.  4.  5.]


In [105]:
for i in B.T:
    print(i)

[ 1.  1.  1.]
[ 1.  2.  3.]
[ 2.  4.  5.]
[ 3.  4.  5.]


In [106]:
B.T?